### ISSUE TITLE
JOSS submission comments

### ISSUE THREAD

**Issue by AoifeHughes** [SMRuggiero/sbmltoodepy#1]
Regarding JOSS review: [https://github.com/openjournals/joss-reviews/issues/1643](https://github.com/openjournals/joss-reviews/issues/1643)

To keep the JOSS review page as clean as possible I'll be making my comments here. 

I've just begun reading though your software package, many of the comments I'll make here are suggestions - anything which I feel is a serious concern I will state as such. 

I'll also make it clear when I've finished. 

Finally, many thanks for making a contribution to open source software! :)

**Comment by AoifeHughes** [comment]
# General comments
- It would be useful to state which range of python 2X / 3.X this software is supporting.
- A brief line on how to install from source would be useful - I see that one is given for installation from pip

# Testing
- Effort has been made to provide this software with testing [TestingPackage Class](https://github.com/SMRuggiero/sbmltoodepy/blob/8abcff615b4ce31e77951ac08eb5fcdddb5af8e3/sbmltoodepy/utilities.py#L77). However it might be more useful if a full unit-testing frame work was used, for example [PyTest](https://docs.pytest.org/en/latest/) (though other frameworks are available). I would say this is quite important, especially for isolating any potential bugs which could crop up across different python versions or software versions.

## Software checked on:

I wouldn't expect python 2.7 to be support, although some holdouts still use it in the scientific community. It would be useful to explicity state which python versions are "officially" supported, as mentioned previously

- Python 3.6 (works)
- Python 3.7 (works)
- Python 2.7 (won't install)

# Software style
- A very minor detail - some practises are not ideal in the formatting of the software and could lead to large errors. For example the use of `from x import *`can lead to unexpected behaviour. A style guide / linter would be helpful [pep8](https://www.python.org/dev/peps/pep-0008/)

# Running the provided Tutorial.md
- The line `pip install sbmltoodepy` can give 2 pieces of confusion.
  1. It will install a potentially different version than the repo cloned in the previous lines
  2. It needs a '!' to be run from jupyter e.g. `!pip install sbmltoodepy`
- Both examples given run and give reproducible results
- It might be worth hosting an .ipynb file in the git repo so that others can directly run when they clone it.

**Comment by AoifeHughes** [comment]
# Community guidelines
- If you see the scope for others' to make pull requests or suggest features then it may be an idea to provide some instructions as to how best do this. 

# Paper clarifications 
- The authors have made comparisons to existing software soultions, although I am unsable to see where or how these are evaluated to their proposed method? Perhaps I have misunderstood, but I think it would be useful to focus on this evaluation and show how this software package improves upon existing methods in more detail in the submitted paper.

**Comment by ashleefv** [comment]
## Running the provided Tutorial.md

We addressed the comments by
- clarifying the case when cloning the repo and pip install make sense together (use on google colab)
- fixing pip install command
- hosting a copy of SBMLtoODEpy.ipynb in the repo

**Comment by AoifeHughes** [comment]
Excellent, thank you for the updates!

**Comment by AnabelSMRuggiero** [comment]
# General Comments

We now specify that the supported versions of python are 3.5, 3.6, and 3.7.

Added comment to README.md about installing from source.

# Software style

Removed all of the "import *" statements. While the updated code on this github repo has been updated, we plan on updating the package on PyPI once all reviewer comments have been addressed.

# Paper Clarifications

In our paper, we compare our work to two other pieces of software.

COPASI- The comparison was intended simply to validate the results of the models generated by SBMLtoODEpy. COPASI uses ODEPACK for its Time Course calculations, which is the same library that scipy's odeint function uses. If the calculations agree, then that suggests SBMLtoODEpy has generated the correct equations.  Furthermore, the targeted niche for SBMLtoODEpy is not the same as COPASI.

Systems Biology Format Converter (SBFC)- SBFC is a better software to compare SBMLtoODEpy to. SBFC converts SBML models into various programing and modeling languages, but notably excludes Python. This gap SBFC's functionality is specifically the target niche of SBMLtoODEpy. Additionally, SBMLtoODEpy is designed to generate code that can be incorporated into other python projects. The Octave/MATLAB scripts generated by SBFC implement the model that neither accept arguments nor return any values. SBMLtoODEpy generates code that implements the model as a class with most methods and members intended to be accessible to other code.

The paper has been updated to better convey the scope and intent of the comparisons.

**Comment by ashleefv** [comment]
# Testing
PyTest could be a good fit for our project, but we expect to include if we have a major update in the future.
