### ISSUE TITLE
Typo in title of paper on JOSS

### ISSUE THREAD

**Issue by hsauro** [SMRuggiero/sbmltoodepy#5]
Looks like the JOSS paper (https://joss.theoj.org/papers/10.21105/joss.01643) has a typo in the first word of the title.

**Comment by ashleefv** [comment]
Thank you for pointing this out.

**Comment by ashleefv** [comment]
We have corrected this in paper.md (along with one other instance). JOSS has been contacted to see about updating.

**Comment by ashleefv** [comment]
This issue has been resolved with JOSS.
